name: "Deploy action"
description: "Deployment of InCogNiTo124 stuff"
inputs:
  vault-password:
    description: "Password for decrypting inventory and private key"
    required: true
outputs: {}
runs:
  using: "docker"
  image: "docker://ghcr.io/incognito124/scaling-lamp:latest"
  args:
    - ${{ inputs.vault-password }}
    - ${{ github.repository }}
  env:
    ANSIBLE_HOST_KEY_CHECKING: False
