- hosts: all
  environment: 
    COMPOSE_FILE: docker-compose.yml,prod.docker-compose.yml
    COMPOSE_PATH_SEPARATOR: ","

  tasks:
    - name: debug extra var
      ansible.builtin.debug:
        var: repo

    - name: ensure repo is cloned
      ansible.builtin.git:
        repo: 'git@github.com:{{ repo }}.git'
        dest: '/opt/{{ repo }}'
        update: false

    - name: docker compose down
      # this should be community.docker.docker_compose
      # but it does not support docker compose v2
      ansible.builtin.command:
        chdir: "/opt/{{ repo }}"
        argv:
          - docker
          - compose
          - down

    - name: update repo
      ansible.builtin.git:
        repo: 'git@github.com:{{ repo }}.git'
        dest: '/opt/{{ repo }}'
        update: true
        version: "origin/master"
        force: true

    - name: check for Makefile
      ansible.builtin.stat:
        path: "/opt/{{ repo }}/Makefile"
      register: makefile

    - name: run make
      community.general.make:
        chdir: "/opt/{{ repo }}"
      when: "(makefile.stat.isreg is defined) and (makefile.stat.isreg)"
      register: make_output

    - name: debug make output
      ansible.builtin.debug:
        msg: "{{ make_output.stdout }}"
      when: "(makefile.stat.isreg is defined) and (makefile.stat.isreg)"

    - name: docker compose build --pull --no-cache
      ansible.builtin.command:
        chdir: "/opt/{{ repo }}"
        argv:
          - docker
          - compose
          - build
          - --pull
          - --no-cache
      async: 500
      poll: 5

    - name: docker compose up -d
      ansible.builtin.command:
        chdir: "/opt/{{ repo }}"
        argv:
          - docker
          - compose 
          - up
          - -d
