- hosts: all
  tasks:
    - name: debug extra var
      ansible.builtin.debug:
        var: repo

    - name: ensure repo is cloned
      ansible.builtin.git:
        repo: 'git@github.com:InCogNiTo124/deploy-test.git'
        dest: '~/InCogNiTo124/deploy-test'
        update: false

    - name: docker compose down
      # this should be community.docker.docker_compose
      # but it does not support docker compose v2
      ansible.builtin.command:
        chdir: "~/InCogNiTo124/deploy-test"
        argv:
          - docker
          - compose
          - down

    - name: update repo
      ansible.builtin.git:
        repo: 'https://github.com/InCogNiTo124/deploy-test.git'
        dest: '~/InCogNiTo124/deploy-test'
        update: true
        version: "origin/master"
        force: true

    - name: check for Makefile
      ansible.builtin.stat:
        path: "~/InCogNiTo124/deploy-test/Makefile"
      register: makefile

    - name: run make
      community.general.make:
        chdir: "~/InCogNiTo124/deploy-test"
      when: "(makefile.stat.isreg is defined) and (makefile.stat.isreg)"
      register: make_output

    - name: debug make output
      ansible.builtin.debug:
        var: make_output.stdout
      when: "(makefile.stat.isreg is defined) and (makefile.stat.isreg)"

    - name: docker compose build --pull --no-cache
      ansible.builtin.command:
        chdir: "~/InCogNiTo124/deploy-test"
        argv:
          - docker
          - compose
          - build
          - --pull
          - --no-cache

    - name: docker compose up -d
      ansible.builtin.command:
        chdir: "~/InCogNiTo124/deploy-test"
        argv:
          - docker
          - compose 
          - up
          - -d
